spring:
  application:
    name: heliophysics-engine
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
nasa:
  api:
    key: ${NASA_API_KEY:cFVWJWrRe4LnLCrV51mkY89TJoYlsBDW3ZEEUNJ6}
    base-url: https://api.nasa.gov
noaa:
  api:
    base-url: https://services.swpc.noaa.gov
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.cosmicpulse: INFO
server:
  port: ${PORT:8080}
